### ISSUE TITLE
Cobra Issue: error when starting the cobra_mic_demo on a raspberry pi 4 

### ISSUE THREAD

**Issue by AbdouBou** [Picovoice/cobra#117]
When trying so lunch the cobra_mic_demo using the python sdk and after well installing the package. an error occurs
### Expected behaviour
The normal start of the cobra_demo_mic  (probability of speech)

### Actual behaviour
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pvcobrademo/cobra_demo_mic.py", line 61, in run
    cobra = pvcobra.create(
  File "/home/pi/.local/lib/python3.9/site-packages/pvcobra/__init__.py", line 30, in create
    return Cobra(library_path=library_path, access_key=access_key)
  File "/home/pi/.local/lib/python3.9/site-packages/pvcobra/cobra.py", line 130, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvcobra.cobra.CobraActivationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/cobra_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/pvcobrademo/cobra_demo_mic.py", line 130, in main
    CobraDemo(
  File "/home/pi/.local/lib/python3.9/site-packages/pvcobrademo/cobra_demo_mic.py", line 95, in run
    recorder.delete()
AttributeError: 'NoneType' object has no attribute 'delete'

### Steps to reproduce the behaviour
Launch the commande cobra_demo_mic --access_key **TOKEN**

on raspbian bullseye 64 system (raspberry pi 4) 2 GB

**Comment by ErisMik** [comment]
I've tested this locally and everything seems to be working okay. Could you please ensure that you have the latest package versions (`pip3 install -U pvcobrademo`) and that you are inputting your access key correctly?

**Comment by AbdouBou** [comment]
@ErisMik  Thank you for your answer you gave me a hint.
Actually, it was a first-time connection issue. there should be a good internet connection in first time you use the cobra demo. now it works.
